apiVersion: apps/v1
kind: Deployment
metadata:
  name: retgyu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retgyu
  template:
    metadata:
      labels:
        app: retgyu
    spec:
      containers:
      - image: okteto.dev/retgyu:latest
        name: retgyu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "888aec1c-1fee-4870-bf40-f72483bb6fe0"
        - name: Vless_Path
          value: "/vlfgbr45"
        - name: Vmess_UUID
          value: "888aec1c-1fee-4870-bf40-f72483bb6fe0"
        - name: Vmess_Path
          value: "/vmfvshy32"
        - name: Share_Path
          value: "/v2link"
